services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    environment:
      # DATABASE
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_PORT=${DB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - DB_POSTGRESDB_SSL_ENABLED=${DB_SSL_ENABLED}
      - DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
      # N8N Config
      - N8N_HOST=${N8N_HOSTNAME}
      - N8N_PROTOCOL=https
      - N8N_TRUST_PROXY=true
      - WEBHOOK_URL=https://${N8N_HOSTNAME}/
      - GENERIC_TIMEZONE=${TIMEZONE}
      - TZ=${TIMEZONE}
      # nginx-proxy
      - VIRTUAL_HOST=${N8N_HOSTNAME}
      - VIRTUAL_PORT=5678
      - LETSENCRYPT_HOST=${N8N_HOSTNAME}
      - HTTPS_METHOD=noredirect
    expose:
      - 5678
    volumes:
      - n8n_storage:/home/node/.n8n
    networks:
      - bridge-net

volumes:
  n8n_storage:

networks:
  bridge-net:
    external: true
